### ISSUE TITLE
Ambiguity in LEIC programme folder

### ISSUE THREAD

**Issue by xploitedd** [i-on-project/integration-data#12]
Currently there are two repositories for LEIC programmes in the calendar term 2020-2021-2, which is ambiguous.

Moreover, the documentation states that the folders should be lowercase named, in which case the majority of the folders don't follow this pattern.

**Comment by grimord** [comment]
Hi @xploitedd ,

Fixed on https://github.com/i-on-project/integration/issues/233 which is then reflected on PR #13 .

Thanks for the report!
