### ISSUE TITLE
Creation and Retrieval Instant deserialization

### ISSUE THREAD

**Issue by xploitedd** [i-on-project/integration-data#15]
Currently, the `creationDateTime` and the `retrievalDateTime` don't follow the Java implementation of [ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601) used when performing the deserialization of an Instant (`Instant#parse`). The Java implementation only seems to support the format with separators for the date and time.

My suggestion is to replace the format, so the applications that use the Integration data don't need to perform custom deserializations.

An example is shown below:

- Current format: `20210421T204916Z`
- Proposed format: `2021-04-21T20:49:16Z`

**Comment by rjcanto** [comment]
Updated the documentation. Will be corrected in the i-on integration output generation.

**Comment by rjcanto** [comment]
[PR 264 of Integration project](https://github.com/i-on-project/integration/pull/264) fixes this.

![image](https://user-images.githubusercontent.com/2482094/123345062-23844080-d54d-11eb-91cc-f9a81c5c8dd1.png)
