### ISSUE TITLE
Wrong Timetable Event Category

### ISSUE THREAD

**Issue by xploitedd** [i-on-project/integration-data#16]
In [here](https://github.com/i-on-project/integration-data#timetables) it's specified that a possible category for a timetable event is `LECTURE-PRACTICE`, however the category used in the timetable files is `LECTURE_PRACTICE` (with an underscore instead of a hyphen.).

**Comment by rjcanto** [comment]
Corrected in the documentation to `LECTURE_PRACTICE`.
