### ISSUE TITLE
Calendar documentation doesn't correspond to actual representation

### ISSUE THREAD

**Issue by xploitedd** [i-on-project/integration-data#21]
From my understanding the `details` key of the calendar has changed to `lectures`, however, the actual representation of the lectures now contains events, whereas in the documentation the lectures contain information about the start and end dates of the lectures, as well as the curricular semesters.

Moreover, I suggest implementing a reviewing procedure, where the master branch contains the reviewed information. This allows Core to function, while also allowing Integration to adapt its output representations.

**Comment by rjcanto** [comment]
Created in a new branch a format as per your review, based on [this year calendar](https://www.isel.pt/media/uploads/OS09P2020_signed.pdf):
https://github.com/i-on-project/integration-data/blob/update-calendar-format/pt.ipl.isel/academic_years/2020-2021/calendar.yaml

Please check if this reflects your feedback. If needed we can schedule a call to go through it.

CC: @grimord

**Comment by xploitedd** [comment]
Thanks for the quick resolution.

Is the master branch going to be a development branch? If yes, will there be a more permanent branch for the Core application to work on?

This is due to the fact that the branch is configured via an environment variable, therefore we would like a stable branch to keep from changing this variable too often.

My idea was that Integration would publish changes to a staging branch and would automatically open a PR from the staging branch to the master, where this PR would require manual review to guarantee that the Core application works with the new changes and that the new data is accurate with the external representation.

**Comment by rjcanto** [comment]
The experimental branch has the processed files, we are making a commit per any new file, and for now the PR has to be opened manually for review. I suggest adding the Integration Core team to the Integration-Data list of reviewers.

For the automatic PR to be achieve it, a new branch has to be created per new output. We'll discuss with the supervisor, but due to the tight schedule until the project delivery on the 21st July, it may be challenging.
